BINGO/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "BINGO"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('prelogin/', include('prelogin.urls')),
    path('game/', include('game.urls'))
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game'
urlpatterns = [
    path('start/<str:me>/<str:oppo>', views.start, name='start'),
    path('processGameState/', views.processGameState, name='processGameState'),
    path('refGame/<str:me>/<str:oppo>', views.refGame, name="refGame")
]

prelogin/urls.py
from django.urls import path
from . import views

app_name = "prelogin"
urlpatterns = [
    path('index/', views.index, name='index')
]

game/models.py
from django.db import models

# Create your models here.

prelogin/models.py
from django.db import models

# Create your models here.

prelogin/forms.py
from django import forms

class NewPlayerForm(forms.Form):
    name = forms.CharField(label="Name")
    oppo = forms.CharField(label="Opponent")
    BINGO_word = forms.CharField(label="Your BINGO! word", max_length=5, min_length=5)

game/views.py
from django.shortcuts import render
from django.http import JsonResponse

import random
import json

GAME_STATE = {}
RANDOM_STATE = {}
CUR_PLAYER = {}
TERMINATE = {}
COLS = [[x for x in range(s, s + 21, 5)] for s in range(5)]
ROWS = [[x for x in range(s, s + 5)] for s in range(0, 21, 5)]
DIAG = [[4*x for x in range(1,6)], [6*x for x in range(5)]]


# Create your views here.
def start(request, me, oppo):
    randomState = list(range(1, 26))
    random.shuffle(randomState)
    RANDOM_STATE[me] = randomState
    players = min(me, oppo) + max(me, oppo)
    CUR_PLAYER[players] = max(me, oppo)
    context = {
        "me": me,
        "oppo": oppo,
        'randomState': randomState
    }
    if players in GAME_STATE:
        context['gamestate'] = GAME_STATE[players]
    else:
        context['gamestate'] = {}

    return render(request, 'game/playground.html', context=context)

def processGameState(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode())

        players = min(data['me'], data['oppo']) + max(data['me'], data['oppo'])
        if players in GAME_STATE:
            GAME_STATE[players].append(int(data['clicked']))
        else:
            GAME_STATE[players] = [int(data['clicked'])]

        CUR_PLAYER[players] = data['oppo']
    
    return JsonResponse(
        {"Foo": "Bar"}
    )

def check_Status(player, players):
    WIN_STATE = []
    
    for row in ROWS:
        ran = []
        for cell in row:
            if RANDOM_STATE[player][cell] not in GAME_STATE[players]:
                break
            ran.append(RANDOM_STATE[player][cell])
        else:
            WIN_STATE.append(ran)

    for col in COLS:
        ran = []
        for cell in col:
            if RANDOM_STATE[player][cell] not in GAME_STATE[players]:
                break
            ran.append(RANDOM_STATE[player][cell])
        else:
            WIN_STATE.append(ran)

    for diag in DIAG:
        ran = []
        for cell in diag:
            if RANDOM_STATE[player][cell] not in GAME_STATE[players]:
                break
            ran.append(RANDOM_STATE[player][cell])
        else:
            WIN_STATE.append(ran)
        
    return WIN_STATE

def refGame(request, me, oppo):
    players = min(me, oppo) + max(me, oppo)
    if players not in GAME_STATE:
        GAME_STATE[players] = []
    
    WIN_STATE_ME = check_Status(me, players)
    WIN_STATE_OPPO = check_Status(oppo, players)

    data = {
        "gamestate": GAME_STATE[players],
        "winstate": WIN_STATE_ME,
        "curplayer": CUR_PLAYER[players]
    }

    if len(WIN_STATE_OPPO) >= 5:
        data['curplayer'] = 'gameover' + oppo
        TERMINATE[me] = True

    if len(WIN_STATE_ME) >= 5:
        data['curplayer'] = 'gameover' + me
        TERMINATE[me] = True
    
    if me in TERMINATE and TERMINATE[me] and oppo in TERMINATE and TERMINATE[oppo]:
        GAME_STATE[players] = []
        CUR_PLAYER[players] = ''
        RANDOM_STATE[me] = []
        RANDOM_STATE[oppo] = []

    return JsonResponse(
        data
    )

prelogin/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import NewPlayerForm

# Create your views here.
def index(request):
    if request.method == 'POST':
        _NewPlayerForm = NewPlayerForm(request.POST)
        if _NewPlayerForm.is_valid():
            me = _NewPlayerForm.cleaned_data['name']
            oppo = _NewPlayerForm.cleaned_data['oppo']
            BINGO_word = _NewPlayerForm.cleaned_data['BINGO_word']

            return HttpResponseRedirect(reverse('game:start', args=(me, oppo)))

    return render(request, 'prelogin/index.html', context={
        "form": NewPlayerForm()
    })

game/templates/game/layout.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
        {% endblock %}
    </head>
    <body bgcolor="#444444">
        {% block body %}
        {% endblock %}
    </body>
</html>

game/templates/game/playground.html
{% extends 'game/layout.html' %}

{% block head %}
    <style>
        h1 {
            font-family: 'Jokerman';
            color: white;
            letter-spacing: 25px;
        }

        h3, h4 {
            color: white;
            font-family: 'Consolas';
        }

        .bingo-default {
            color: white;
            font-size: xx-large;
            padding: 20px;
            word-spacing: 20px;
            font-family: Jokerman;
            font-weight: 100;
        }

        .won {
            font-size: xx-large;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            color: darkgreen;
            font-weight: 100;
        }

        .lost {
            font-weight: 100;
            font-size: xx-large;
            color: darkred;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }
    </style>
    <title>BINGO!</title>
{% endblock %}

{% block body %}
    <center>
        <div>
            <h3>Hello {{ me }}</h3>
            <h4>You are playing against {{ oppo }}</h4>
        </div>
        <div id="game" style="pointer-events: none;">
        </div>
        <br><br>
        <div>
            <span class="bingo-default" id="letter0">B</span>
            <span class="bingo-default" id="letter1">I</span>
            <span class="bingo-default" id="letter2">N</span>
            <span class="bingo-default" id="letter3">G</span>
            <span class="bingo-default" id="letter4">O</span>
        </div>
        <div class="won" style="display: none;">
            You Won the match {{ me }}! :)
        </div>
        <div class="lost" style="display: none">
            You Lost the match {{ me }}! :(
        </div>
    </center>
    <script>
        let csrftoken = '{{ csrf_token }}';
        let randomState = '{{ randomState }}';
        randomState = JSON.parse(randomState);
        for (let i = 0; i < 25; i++) {
            const button = document.createElement('input');
            button.type = 'button';
            button.id = 'but' + randomState[i];
            button.value = randomState[i];
            button.style.width = '50px';
            button.style.height = '50px';
            button.style.border = 'solid #000000 5px';
            button.style.margin = '2px';

            button.onmouseover = () => {
                button.style.backgroundColor = '#000000';
                button.style.color = '#ffffff';
                button.style.cursor = 'pointer';
            }

            button.onmouseleave = () => {
                button.style.backgroundColor = '#ffffff';
                button.style.color = '#000000';
                button.style.cursor = 'default';
            }

            button.onclick = () => {
                document.querySelector("#game").style.pointerEvents = 'none';
                button.style.backgroundColor = '#009900';
                button.style.color = '#ffffff';

                if (button.onmouseleave === null) return;
                if (button.onmouseover === null) return;

                var csrftoekn = '{{ csrf_token }}';
                fetch("{% url 'game:processGameState' %}", {
                    method: "POST",
                    body: JSON.stringify({
                        'clicked': button.value,
                        'me': '{{ me }}',
                        'oppo': '{{ oppo }}'
                    }),
                    headers: {"X-CSRFToken": csrftoken}
                }).then(result => {
                    console.log(result.text());
                })

                button.onmouseleave = null;
                button.onmouseover = null;
            }
            
            if (i % 5 == 0) {
                document.querySelector('#game')
                .appendChild(document.createElement('br'));

            }
            document.querySelector("#game")
            .appendChild(button);
        }
    </script>
    <script>
        clickButton = function(value) {
            var button = document.querySelector(`#but${value}`);
            if (button) {
                button.onmouseleave = null;
                button.onmouseover = null;
                button.click();
            }
        }

        winstatefn = function(value) {
            var button = document.querySelector(`#but${value}`);
            if (button) {
                button.style.backgroundColor = 'darkgray';
            }
        }
    </script>
    {% for val in gamestate %}
    <script>
        clickButton('{{ val }}')
    </script>
    {% endfor %}
    <script>
        getGameState = setInterval(function() {
            fetch("{% url 'game:refGame' me oppo %}")
            .then(res => res.json())
            .then(data => {
                data['gamestate'].forEach(clickButton);
                for (let i = 0; i < data['winstate'].length; i++) {
                    document.querySelector(`#letter${i}`)
                    .style.color = 'green';
                }
                data['winstate'].forEach((arr) => {
                    arr.forEach(winstatefn);
                })
                if (data['curplayer'] == ('gameover' + '{{ me }}')) {
                    document.querySelector('.won')
                    .style.display = 'block';
                    document.body.style.pointerEvents = 'none';
                    clearInterval(getGameState);
                    return;

                } else if (data['curplayer'] == ('gameover' + '{{ oppo }}')) {
                    document.querySelector('.lost')
                    .style.display = 'block';
                    document.body.style.pointerEvents = 'none';
                    clearInterval(getGameState);
                    return;

                } else if (data['curplayer'] == '{{ me }}') {
                    document.querySelector("#game").style.pointerEvents = 'auto';
                } else {
                    document.querySelector("#game").style.pointerEvents = 'none';
                }
            })
            .catch(error => console.error(error));
        }, 1000);
    </script>
{% endblock %}

prelogin/templates/prelogin/index.html
{% extends 'prelogin/layout.html' %}

{% block body %}
    <form action="{% url 'prelogin:index' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

prelogin/templates/prelogin/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>play BINGO!</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>